.TH "DB" 3 "Вс 13 Авг 2017" "Version 0.4" "PROF site" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:mysqli\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($serverName, $login, $pass, $db)"
.br
.ti -1c
.RI "\fBquery\fP ($query, $func='', $error_log=true)"
.br
.ti -1c
.RI "\fBq\fP ($select, $from, $where=array())"
.br
.ti -1c
.RI "\fBthrow_error\fP ($funcname='')"
.br
.ti -1c
.RI "\fBescape\fP ($string)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Перегружает некоторые функции стандартного класса mysqli\&. 
.SH "Методы"
.PP 
.SS "q ( $select,  $from,  $where = \fCarray()\fP)"
Функция делает запрос в базу данных с заданными параметрами\&. Запрещается использовать для выборки, в которой участвует более чем 1 таблица\&. Для этого необходимо использовать функцию \fBquery()\fP 
.PP
\fBАргументы:\fP
.RS 4
\fI$select\fP Поля для выбора 
.br
\fI$from\fP Таблица, из которой идет выбор 
.br
\fI$where\fP Ассоциативный массив, где ключами являются поля, а значениями необходимые для отсеивания значения в соответствующих полях (могут быть массивы для сравнения на равенство)\&. 
.RE
.PP

.SS "query ( $query,  $func = \fC''\fP,  $error_log = \fCtrue\fP)"

.PP
\fBАргументы:\fP
.RS 4
\fI$query\fP 
.br
\fI$error_log\fP 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для PROF site из исходного текста\&.
