.TH "Main" 3 "Вс 13 Авг 2017" "Version 0.4" "PROF site" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBuseController\fP ($cName, $settings=array())"
.br
.in -1c
.SH "Подробное описание"
.PP 
Основной класс для управления системой\&. 
.SH "Методы"
.PP 
.SS "useController ( $cName,  $settings = \fCarray()\fP)"
Подключает контроллер с именем $cName\&. 
.PP
\fBАргументы:\fP
.RS 4
\fI$cName\fP Название подключаемого контроллера\&. 
.br
\fI$settings\fP Параметры подключения контроллера\&. 
.RE
.PP
\fBВозвращает:\fP
.RS 4
массив с результатом работы контроллера\&. Используется на странице подключения\&. Необходимо записать его в переменную и вывести результат в виде необходимого HTML\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для PROF site из исходного текста\&.
