.TH "User" 3 "Вс 13 Авг 2017" "Version 0.4" "PROF site" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetSurname\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetThirdName\fP ()"
.br
.ti -1c
.RI "\fBgetFullName\fP ()"
.br
.ti -1c
.RI "\fBgetSurnameName\fP ()"
.br
.ti -1c
.RI "\fBgetGroup\fP ()"
.br
.ti -1c
.RI "\fBgetFaculty\fP ()"
.br
.ti -1c
.RI "\fBgetLevel\fP ()"
.br
.ti -1c
.RI "\fBgetEventsResponsibleCount\fP ()"
.br
.ti -1c
.RI "\fBlogIn\fP ($login, $password)"
.br
.ti -1c
.RI "\fBCountEventsResponsible\fP ()"
.br
.ti -1c
.RI "\fBgetNumPostNotes\fP ()"
.br
.ti -1c
.RI "\fBgetNumEventNotes\fP ()"
.br
.ti -1c
.RI "\fBgetNumTaskNotes\fP ()"
.br
.ti -1c
.RI "\fBgetNumSocNotes\fP ()"
.br
.ti -1c
.RI "\fBgetNumNotes\fP ()"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static \fBId\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс пользователя\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для PROF site из исходного текста\&.
